// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package domain

import (
	"context"
	"sync"
	"time"
)

// Ensure, that AuthorizationCodeRepositoryMock does implement AuthorizationCodeRepository.
// If this is not the case, regenerate this file with moq.
var _ AuthorizationCodeRepository = &AuthorizationCodeRepositoryMock{}

// AuthorizationCodeRepositoryMock is a mock implementation of AuthorizationCodeRepository.
//
//	func TestSomethingThatUsesAuthorizationCodeRepository(t *testing.T) {
//
//		// make and configure a mocked AuthorizationCodeRepository
//		mockedAuthorizationCodeRepository := &AuthorizationCodeRepositoryMock{
//			FindAuthorizationCodeFunc: func(ctx context.Context, code string) (AuthorizationCode, error) {
//				panic("mock out the FindAuthorizationCode method")
//			},
//			FindValidAuthorizationCodeFunc: func(ctx context.Context, code string, expiresAt time.Time) (AuthorizationCode, error) {
//				panic("mock out the FindValidAuthorizationCode method")
//			},
//			RevokeCodeFunc: func(ctx context.Context, code string) error {
//				panic("mock out the RevokeCode method")
//			},
//			StoreAuthorizationCodeFunc: func(ctx context.Context, p StoreAuthorizationCodeParams) (string, error) {
//				panic("mock out the StoreAuthorizationCode method")
//			},
//		}
//
//		// use mockedAuthorizationCodeRepository in code that requires AuthorizationCodeRepository
//		// and then make assertions.
//
//	}
type AuthorizationCodeRepositoryMock struct {
	// FindAuthorizationCodeFunc mocks the FindAuthorizationCode method.
	FindAuthorizationCodeFunc func(ctx context.Context, code string) (AuthorizationCode, error)

	// FindValidAuthorizationCodeFunc mocks the FindValidAuthorizationCode method.
	FindValidAuthorizationCodeFunc func(ctx context.Context, code string, expiresAt time.Time) (AuthorizationCode, error)

	// RevokeCodeFunc mocks the RevokeCode method.
	RevokeCodeFunc func(ctx context.Context, code string) error

	// StoreAuthorizationCodeFunc mocks the StoreAuthorizationCode method.
	StoreAuthorizationCodeFunc func(ctx context.Context, p StoreAuthorizationCodeParams) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// FindAuthorizationCode holds details about calls to the FindAuthorizationCode method.
		FindAuthorizationCode []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Code is the code argument value.
			Code string
		}
		// FindValidAuthorizationCode holds details about calls to the FindValidAuthorizationCode method.
		FindValidAuthorizationCode []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Code is the code argument value.
			Code string
			// ExpiresAt is the expiresAt argument value.
			ExpiresAt time.Time
		}
		// RevokeCode holds details about calls to the RevokeCode method.
		RevokeCode []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Code is the code argument value.
			Code string
		}
		// StoreAuthorizationCode holds details about calls to the StoreAuthorizationCode method.
		StoreAuthorizationCode []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// P is the p argument value.
			P StoreAuthorizationCodeParams
		}
	}
	lockFindAuthorizationCode      sync.RWMutex
	lockFindValidAuthorizationCode sync.RWMutex
	lockRevokeCode                 sync.RWMutex
	lockStoreAuthorizationCode     sync.RWMutex
}

// FindAuthorizationCode calls FindAuthorizationCodeFunc.
func (mock *AuthorizationCodeRepositoryMock) FindAuthorizationCode(ctx context.Context, code string) (AuthorizationCode, error) {
	if mock.FindAuthorizationCodeFunc == nil {
		panic("AuthorizationCodeRepositoryMock.FindAuthorizationCodeFunc: method is nil but AuthorizationCodeRepository.FindAuthorizationCode was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Code string
	}{
		Ctx:  ctx,
		Code: code,
	}
	mock.lockFindAuthorizationCode.Lock()
	mock.calls.FindAuthorizationCode = append(mock.calls.FindAuthorizationCode, callInfo)
	mock.lockFindAuthorizationCode.Unlock()
	return mock.FindAuthorizationCodeFunc(ctx, code)
}

// FindAuthorizationCodeCalls gets all the calls that were made to FindAuthorizationCode.
// Check the length with:
//
//	len(mockedAuthorizationCodeRepository.FindAuthorizationCodeCalls())
func (mock *AuthorizationCodeRepositoryMock) FindAuthorizationCodeCalls() []struct {
	Ctx  context.Context
	Code string
} {
	var calls []struct {
		Ctx  context.Context
		Code string
	}
	mock.lockFindAuthorizationCode.RLock()
	calls = mock.calls.FindAuthorizationCode
	mock.lockFindAuthorizationCode.RUnlock()
	return calls
}

// FindValidAuthorizationCode calls FindValidAuthorizationCodeFunc.
func (mock *AuthorizationCodeRepositoryMock) FindValidAuthorizationCode(ctx context.Context, code string, expiresAt time.Time) (AuthorizationCode, error) {
	if mock.FindValidAuthorizationCodeFunc == nil {
		panic("AuthorizationCodeRepositoryMock.FindValidAuthorizationCodeFunc: method is nil but AuthorizationCodeRepository.FindValidAuthorizationCode was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Code      string
		ExpiresAt time.Time
	}{
		Ctx:       ctx,
		Code:      code,
		ExpiresAt: expiresAt,
	}
	mock.lockFindValidAuthorizationCode.Lock()
	mock.calls.FindValidAuthorizationCode = append(mock.calls.FindValidAuthorizationCode, callInfo)
	mock.lockFindValidAuthorizationCode.Unlock()
	return mock.FindValidAuthorizationCodeFunc(ctx, code, expiresAt)
}

// FindValidAuthorizationCodeCalls gets all the calls that were made to FindValidAuthorizationCode.
// Check the length with:
//
//	len(mockedAuthorizationCodeRepository.FindValidAuthorizationCodeCalls())
func (mock *AuthorizationCodeRepositoryMock) FindValidAuthorizationCodeCalls() []struct {
	Ctx       context.Context
	Code      string
	ExpiresAt time.Time
} {
	var calls []struct {
		Ctx       context.Context
		Code      string
		ExpiresAt time.Time
	}
	mock.lockFindValidAuthorizationCode.RLock()
	calls = mock.calls.FindValidAuthorizationCode
	mock.lockFindValidAuthorizationCode.RUnlock()
	return calls
}

// RevokeCode calls RevokeCodeFunc.
func (mock *AuthorizationCodeRepositoryMock) RevokeCode(ctx context.Context, code string) error {
	if mock.RevokeCodeFunc == nil {
		panic("AuthorizationCodeRepositoryMock.RevokeCodeFunc: method is nil but AuthorizationCodeRepository.RevokeCode was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Code string
	}{
		Ctx:  ctx,
		Code: code,
	}
	mock.lockRevokeCode.Lock()
	mock.calls.RevokeCode = append(mock.calls.RevokeCode, callInfo)
	mock.lockRevokeCode.Unlock()
	return mock.RevokeCodeFunc(ctx, code)
}

// RevokeCodeCalls gets all the calls that were made to RevokeCode.
// Check the length with:
//
//	len(mockedAuthorizationCodeRepository.RevokeCodeCalls())
func (mock *AuthorizationCodeRepositoryMock) RevokeCodeCalls() []struct {
	Ctx  context.Context
	Code string
} {
	var calls []struct {
		Ctx  context.Context
		Code string
	}
	mock.lockRevokeCode.RLock()
	calls = mock.calls.RevokeCode
	mock.lockRevokeCode.RUnlock()
	return calls
}

// StoreAuthorizationCode calls StoreAuthorizationCodeFunc.
func (mock *AuthorizationCodeRepositoryMock) StoreAuthorizationCode(ctx context.Context, p StoreAuthorizationCodeParams) (string, error) {
	if mock.StoreAuthorizationCodeFunc == nil {
		panic("AuthorizationCodeRepositoryMock.StoreAuthorizationCodeFunc: method is nil but AuthorizationCodeRepository.StoreAuthorizationCode was just called")
	}
	callInfo := struct {
		Ctx context.Context
		P   StoreAuthorizationCodeParams
	}{
		Ctx: ctx,
		P:   p,
	}
	mock.lockStoreAuthorizationCode.Lock()
	mock.calls.StoreAuthorizationCode = append(mock.calls.StoreAuthorizationCode, callInfo)
	mock.lockStoreAuthorizationCode.Unlock()
	return mock.StoreAuthorizationCodeFunc(ctx, p)
}

// StoreAuthorizationCodeCalls gets all the calls that were made to StoreAuthorizationCode.
// Check the length with:
//
//	len(mockedAuthorizationCodeRepository.StoreAuthorizationCodeCalls())
func (mock *AuthorizationCodeRepositoryMock) StoreAuthorizationCodeCalls() []struct {
	Ctx context.Context
	P   StoreAuthorizationCodeParams
} {
	var calls []struct {
		Ctx context.Context
		P   StoreAuthorizationCodeParams
	}
	mock.lockStoreAuthorizationCode.RLock()
	calls = mock.calls.StoreAuthorizationCode
	mock.lockStoreAuthorizationCode.RUnlock()
	return calls
}
