// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package domain

import (
	"context"
	"sync"
)

// Ensure, that RefreshTokenRepositoryMock does implement RefreshTokenRepository.
// If this is not the case, regenerate this file with moq.
var _ RefreshTokenRepository = &RefreshTokenRepositoryMock{}

// RefreshTokenRepositoryMock is a mock implementation of RefreshTokenRepository.
//
//	func TestSomethingThatUsesRefreshTokenRepository(t *testing.T) {
//
//		// make and configure a mocked RefreshTokenRepository
//		mockedRefreshTokenRepository := &RefreshTokenRepositoryMock{
//			FindRefreshTokenFunc: func(ctx context.Context, refreshToken string) (RefreshToken, error) {
//				panic("mock out the FindRefreshToken method")
//			},
//			RevokeRefreshTokenFunc: func(ctx context.Context, refreshToken string) error {
//				panic("mock out the RevokeRefreshToken method")
//			},
//			StoreRefreshTokenFunc: func(ctx context.Context, t RefreshToken) error {
//				panic("mock out the StoreRefreshToken method")
//			},
//		}
//
//		// use mockedRefreshTokenRepository in code that requires RefreshTokenRepository
//		// and then make assertions.
//
//	}
type RefreshTokenRepositoryMock struct {
	// FindRefreshTokenFunc mocks the FindRefreshToken method.
	FindRefreshTokenFunc func(ctx context.Context, refreshToken string) (RefreshToken, error)

	// RevokeRefreshTokenFunc mocks the RevokeRefreshToken method.
	RevokeRefreshTokenFunc func(ctx context.Context, refreshToken string) error

	// StoreRefreshTokenFunc mocks the StoreRefreshToken method.
	StoreRefreshTokenFunc func(ctx context.Context, t RefreshToken) error

	// calls tracks calls to the methods.
	calls struct {
		// FindRefreshToken holds details about calls to the FindRefreshToken method.
		FindRefreshToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RefreshToken is the refreshToken argument value.
			RefreshToken string
		}
		// RevokeRefreshToken holds details about calls to the RevokeRefreshToken method.
		RevokeRefreshToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RefreshToken is the refreshToken argument value.
			RefreshToken string
		}
		// StoreRefreshToken holds details about calls to the StoreRefreshToken method.
		StoreRefreshToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// T is the t argument value.
			T RefreshToken
		}
	}
	lockFindRefreshToken   sync.RWMutex
	lockRevokeRefreshToken sync.RWMutex
	lockStoreRefreshToken  sync.RWMutex
}

// FindRefreshToken calls FindRefreshTokenFunc.
func (mock *RefreshTokenRepositoryMock) FindRefreshToken(ctx context.Context, refreshToken string) (RefreshToken, error) {
	if mock.FindRefreshTokenFunc == nil {
		panic("RefreshTokenRepositoryMock.FindRefreshTokenFunc: method is nil but RefreshTokenRepository.FindRefreshToken was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		RefreshToken string
	}{
		Ctx:          ctx,
		RefreshToken: refreshToken,
	}
	mock.lockFindRefreshToken.Lock()
	mock.calls.FindRefreshToken = append(mock.calls.FindRefreshToken, callInfo)
	mock.lockFindRefreshToken.Unlock()
	return mock.FindRefreshTokenFunc(ctx, refreshToken)
}

// FindRefreshTokenCalls gets all the calls that were made to FindRefreshToken.
// Check the length with:
//
//	len(mockedRefreshTokenRepository.FindRefreshTokenCalls())
func (mock *RefreshTokenRepositoryMock) FindRefreshTokenCalls() []struct {
	Ctx          context.Context
	RefreshToken string
} {
	var calls []struct {
		Ctx          context.Context
		RefreshToken string
	}
	mock.lockFindRefreshToken.RLock()
	calls = mock.calls.FindRefreshToken
	mock.lockFindRefreshToken.RUnlock()
	return calls
}

// RevokeRefreshToken calls RevokeRefreshTokenFunc.
func (mock *RefreshTokenRepositoryMock) RevokeRefreshToken(ctx context.Context, refreshToken string) error {
	if mock.RevokeRefreshTokenFunc == nil {
		panic("RefreshTokenRepositoryMock.RevokeRefreshTokenFunc: method is nil but RefreshTokenRepository.RevokeRefreshToken was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		RefreshToken string
	}{
		Ctx:          ctx,
		RefreshToken: refreshToken,
	}
	mock.lockRevokeRefreshToken.Lock()
	mock.calls.RevokeRefreshToken = append(mock.calls.RevokeRefreshToken, callInfo)
	mock.lockRevokeRefreshToken.Unlock()
	return mock.RevokeRefreshTokenFunc(ctx, refreshToken)
}

// RevokeRefreshTokenCalls gets all the calls that were made to RevokeRefreshToken.
// Check the length with:
//
//	len(mockedRefreshTokenRepository.RevokeRefreshTokenCalls())
func (mock *RefreshTokenRepositoryMock) RevokeRefreshTokenCalls() []struct {
	Ctx          context.Context
	RefreshToken string
} {
	var calls []struct {
		Ctx          context.Context
		RefreshToken string
	}
	mock.lockRevokeRefreshToken.RLock()
	calls = mock.calls.RevokeRefreshToken
	mock.lockRevokeRefreshToken.RUnlock()
	return calls
}

// StoreRefreshToken calls StoreRefreshTokenFunc.
func (mock *RefreshTokenRepositoryMock) StoreRefreshToken(ctx context.Context, t RefreshToken) error {
	if mock.StoreRefreshTokenFunc == nil {
		panic("RefreshTokenRepositoryMock.StoreRefreshTokenFunc: method is nil but RefreshTokenRepository.StoreRefreshToken was just called")
	}
	callInfo := struct {
		Ctx context.Context
		T   RefreshToken
	}{
		Ctx: ctx,
		T:   t,
	}
	mock.lockStoreRefreshToken.Lock()
	mock.calls.StoreRefreshToken = append(mock.calls.StoreRefreshToken, callInfo)
	mock.lockStoreRefreshToken.Unlock()
	return mock.StoreRefreshTokenFunc(ctx, t)
}

// StoreRefreshTokenCalls gets all the calls that were made to StoreRefreshToken.
// Check the length with:
//
//	len(mockedRefreshTokenRepository.StoreRefreshTokenCalls())
func (mock *RefreshTokenRepositoryMock) StoreRefreshTokenCalls() []struct {
	Ctx context.Context
	T   RefreshToken
} {
	var calls []struct {
		Ctx context.Context
		T   RefreshToken
	}
	mock.lockStoreRefreshToken.RLock()
	calls = mock.calls.StoreRefreshToken
	mock.lockStoreRefreshToken.RUnlock()
	return calls
}
