name: LintAndTest

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN can be read directly from reusable workflow
          workdir: ${{ inputs.target }}
          golangci_lint_flags: "--config=.golangci.yml --timeout=5m ./..."
          fail_on_error: true
          reporter: "github-pr-review"
