[env]
# インラインで環境変数を定義可能
ENV_NAME = "develop"

# .env に設定された環境変数を反映する
#mise.file = ".env"

[tools]
go = "1.24"
node = "22.9.0"

[tasks.setup]
description = "Setup project"
run = ["mise i", "go mod download", "npm i -g yarn"]

[tasks.build]
description = "Build"
run = "docker compose build"

[tasks.test]
description = "Run tests"
run = ["(cd oauth2 && go test ./...)", "& (cd api && go test ./...)"]

[tasks.fmt]
description = "Run go fmt"
run = [
  "(cd oauth2 && go mod tidy && go fmt ./...)",
  "(cd api && go mod tidy && go fmt ./...)",
]

[tasks.generate]
description = "Run go generate"
run = ["(cd oauth2 && go generate ./...)", "(cd api && go generate ./...)"]
