services:
  server:
    build:
      context: ./oauth2
      target: development
    container_name: server
    ports:
      - 8080:8080
    environment:
      DBHost: database
      DBPort: "5432"
      DBUser: app
      DBPassword: pass
      DBName: auth
      GIN_MODE: debug
    volumes:
      - ./oauth2:/src
    depends_on:
      - database
      - session
  api:
    build:
      context: ./api
      target: development
    container_name: api
    ports:
      - 18080:18080
    environment:
      DBHost: database
      DBPort: "5432"
      DBUser: app
      DBPassword: pass
      DBName: auth
    volumes:
      - ./api:/src
    depends_on:
      - database
      - session
  database:
    build:
      context: ./docker/database
    container_name: database
    restart: always
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
  session:
    build:
      context: ./docker/session
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
volumes:
  redisdata:
