services:
  server:
    build:
      context: ./oauth2
      target: development
    container_name: server
    ports:
      - 8080:8080
    environment:
      DBHost: database
      DBPort: "5432"
      DBUser: app
      DBPassword: pass
      DBName: auth
      GIN_MODE: debug
    volumes:
      - ./oauth2:/src
    depends_on:
      database:
        condition: service_healthy
      session:
        condition: service_healthy
  api:
    build:
      context: ./api
      target: development
    container_name: api
    ports:
      - 18080:18080
    environment:
      DBHost: database
      DBPort: "5432"
      DBUser: app
      DBPassword: pass
      DBName: auth
    volumes:
      - ./api:/src
    depends_on:
      - database
      - session
  database:
    build:
      context: ./docker/database
    container_name: database
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "psql -U admin -d auth -c 'SELECT 1 FROM posts LIMIT 1;'"]
      interval: 5s
      timeout: 10s
      retries: 5
  session:
    build:
      context: ./docker/session
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -h localhost ping | grep PONG"]
      interval: 5s
      timeout: 10s
      retries: 5
volumes:
  pgdata:
  redisdata:
