# This configuration file is not a recommendation.
#
# We intentionally use a limited set of linters.
# This configuration file is used with different version of golangci-lint to avoid regressions:
# the linters can change between version,
# their configuration may be not compatible or their reports can be different,
# and this can break some of our tests.
# Also, some linters are not relevant for the project (e.g. linters related to SQL).
#
# We have specific constraints, so we use a specific configuration.
#
# See the file `.golangci.reference.yml` to have a list of all available configuration options.

linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: -1 # the number of lines (code + empty lines) is not a right metric and leads to code without empty line or one-liner.
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 3
  gocyclo:
    min-complexity: 15
  godox:
    keywords:
      - FIXME
  gofmt:
    rewrite-rules:
      - pattern: "interface{}"
        replacement: "any"
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  mnd:
    # don't include the "operation" and "assign"
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - "0"
      - "1"
      - "2"
      - "3"
    ignored-functions:
      - strings.SplitN
  govet:
    enable:
      - shadow
    settings:
      shadow:
        strict: true
  errorlint:
    asserts: false
  lll:
    line-length: 140
  misspell:
    locale: US
    ignore-words:
      - "importas" # linter name
  revive:
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#import-shadowing
      - name: import-shadowing
        severity: warning
        disabled: false
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#empty-block
      - name: empty-block
        severity: warning
        disabled: false
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#empty-lines
      - name: empty-lines
        severity: warning
        disabled: false
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#use-any
      - name: use-any
        severity: warning
        disabled: false

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - copyloopvar
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace

  # This list of linters is not a recommendation (same thing for all this configuration file).
  # We intentionally use a limited set of linters.
  # See the comment on top of this file.

issues:
  exclude-rules:
    - path: (.+)_test\.go
      linters:
        - dupl
        - mnd
        - lll

    # The logic of creating a linter is similar between linters, it's not duplication.
    - path: pkg/golinters
      linters:
        - dupl

    # Deprecated configuration options.
    - path: pkg/commands/run.go
      linters: [staticcheck]
      text: "SA1019: c.cfg.Run.ShowStats is deprecated: use Output.ShowStats instead."

    # Deprecated linter options.
    - path: pkg/golinters/errcheck/errcheck.go
      linters: [staticcheck]
      text: "SA1019: errCfg.Exclude is deprecated: use ExcludeFunctions instead"
    - path: pkg/golinters/errcheck/errcheck.go
      linters: [staticcheck]
      text: "SA1019: errCfg.Ignore is deprecated: use ExcludeFunctions instead"
    - path: pkg/golinters/govet/govet.go
      linters: [staticcheck]
      text: "SA1019: cfg.CheckShadowing is deprecated: the linter should be enabled inside Enable."
    - path: pkg/golinters/godot/godot.go
      linters: [staticcheck]
      text: "SA1019: settings.CheckAll is deprecated: use Scope instead"
    - path: pkg/golinters/gci/gci.go
      linters: [staticcheck]
      text: "SA1019: settings.LocalPrefixes is deprecated: use Sections instead."
    - path: pkg/golinters/mnd/mnd.go
      linters: [staticcheck]
      text: "SA1019: settings.Settings is deprecated: use root level settings instead."
    - path: pkg/golinters/mnd/mnd.go
      linters: [staticcheck]
      text: "SA1019: config.GoMndSettings is deprecated: use MndSettings."

    # Related to `run.go`, it cannot be removed.
    - path: pkg/golinters/gofumpt/gofumpt.go
      linters: [staticcheck]
      text: "SA1019: settings.LangVersion is deprecated: use the global `run.go` instead."
    - path: pkg/golinters/internal/staticcheck_common.go
      linters: [staticcheck]
      text: "SA1019: settings.GoVersion is deprecated: use the global `run.go` instead."
    - path: pkg/lint/lintersdb/manager.go
      linters: [staticcheck]
      text: "SA1019: (.+).(GoVersion|LangVersion) is deprecated: use the global `run.go` instead."

    # Based on existing code, the modifications should be limited to make maintenance easier.
    - path: pkg/golinters/unused/unused.go
      linters: [gocritic]
      text: "rangeValCopy: each iteration copies 160 bytes \\(consider pointers or indexing\\)"
    - linters:
        - errcheck
      text: "`c.Error` is not checked"
    - linters:
        - errcheck
      text: "SetMeta` is not checked"
  exclude-dirs:
    - test/testdata_etc # test files
    - internal/cache # extracted from Go code
    - internal/renameio # extracted from Go code
    - internal/robustio # extracted from Go code

run:
  timeout: 5m
  issues-exit-code: 1 # 警告があればエラーとしてジョブが失敗する

