// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package auth

import (
	"github.com/sntkn/go-oauth2/oauth2/internal/entity"
	"sync"
)

// Ensure, that CreateTokenByCodeUsecaseMock does implement CreateTokenByCodeUsecase.
// If this is not the case, regenerate this file with moq.
var _ CreateTokenByCodeUsecase = &CreateTokenByCodeUsecaseMock{}

// CreateTokenByCodeUsecaseMock is a mock implementation of CreateTokenByCodeUsecase.
//
//	func TestSomethingThatUsesCreateTokenByCodeUsecase(t *testing.T) {
//
//		// make and configure a mocked CreateTokenByCodeUsecase
//		mockedCreateTokenByCodeUsecase := &CreateTokenByCodeUsecaseMock{
//			InvokeFunc: func(authCode string) (*entity.AuthTokens, error) {
//				panic("mock out the Invoke method")
//			},
//		}
//
//		// use mockedCreateTokenByCodeUsecase in code that requires CreateTokenByCodeUsecase
//		// and then make assertions.
//
//	}
type CreateTokenByCodeUsecaseMock struct {
	// InvokeFunc mocks the Invoke method.
	InvokeFunc func(authCode string) (*entity.AuthTokens, error)

	// calls tracks calls to the methods.
	calls struct {
		// Invoke holds details about calls to the Invoke method.
		Invoke []struct {
			// AuthCode is the authCode argument value.
			AuthCode string
		}
	}
	lockInvoke sync.RWMutex
}

// Invoke calls InvokeFunc.
func (mock *CreateTokenByCodeUsecaseMock) Invoke(authCode string) (*entity.AuthTokens, error) {
	if mock.InvokeFunc == nil {
		panic("CreateTokenByCodeUsecaseMock.InvokeFunc: method is nil but CreateTokenByCodeUsecase.Invoke was just called")
	}
	callInfo := struct {
		AuthCode string
	}{
		AuthCode: authCode,
	}
	mock.lockInvoke.Lock()
	mock.calls.Invoke = append(mock.calls.Invoke, callInfo)
	mock.lockInvoke.Unlock()
	return mock.InvokeFunc(authCode)
}

// InvokeCalls gets all the calls that were made to Invoke.
// Check the length with:
//
//	len(mockedCreateTokenByCodeUsecase.InvokeCalls())
func (mock *CreateTokenByCodeUsecaseMock) InvokeCalls() []struct {
	AuthCode string
} {
	var calls []struct {
		AuthCode string
	}
	mock.lockInvoke.RLock()
	calls = mock.calls.Invoke
	mock.lockInvoke.RUnlock()
	return calls
}
