// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package auth

import (
	"github.com/sntkn/go-oauth2/oauth2/internal/entity"
	"sync"
)

// Ensure, that CreateTokenByRefreshTokenUsecaseMock does implement CreateTokenByRefreshTokenUsecase.
// If this is not the case, regenerate this file with moq.
var _ CreateTokenByRefreshTokenUsecase = &CreateTokenByRefreshTokenUsecaseMock{}

// CreateTokenByRefreshTokenUsecaseMock is a mock implementation of CreateTokenByRefreshTokenUsecase.
//
//	func TestSomethingThatUsesCreateTokenByRefreshTokenUsecase(t *testing.T) {
//
//		// make and configure a mocked CreateTokenByRefreshTokenUsecase
//		mockedCreateTokenByRefreshTokenUsecase := &CreateTokenByRefreshTokenUsecaseMock{
//			InvokeFunc: func(refreshToken string) (*entity.AuthTokens, error) {
//				panic("mock out the Invoke method")
//			},
//		}
//
//		// use mockedCreateTokenByRefreshTokenUsecase in code that requires CreateTokenByRefreshTokenUsecase
//		// and then make assertions.
//
//	}
type CreateTokenByRefreshTokenUsecaseMock struct {
	// InvokeFunc mocks the Invoke method.
	InvokeFunc func(refreshToken string) (*entity.AuthTokens, error)

	// calls tracks calls to the methods.
	calls struct {
		// Invoke holds details about calls to the Invoke method.
		Invoke []struct {
			// RefreshToken is the refreshToken argument value.
			RefreshToken string
		}
	}
	lockInvoke sync.RWMutex
}

// Invoke calls InvokeFunc.
func (mock *CreateTokenByRefreshTokenUsecaseMock) Invoke(refreshToken string) (*entity.AuthTokens, error) {
	if mock.InvokeFunc == nil {
		panic("CreateTokenByRefreshTokenUsecaseMock.InvokeFunc: method is nil but CreateTokenByRefreshTokenUsecase.Invoke was just called")
	}
	callInfo := struct {
		RefreshToken string
	}{
		RefreshToken: refreshToken,
	}
	mock.lockInvoke.Lock()
	mock.calls.Invoke = append(mock.calls.Invoke, callInfo)
	mock.lockInvoke.Unlock()
	return mock.InvokeFunc(refreshToken)
}

// InvokeCalls gets all the calls that were made to Invoke.
// Check the length with:
//
//	len(mockedCreateTokenByRefreshTokenUsecase.InvokeCalls())
func (mock *CreateTokenByRefreshTokenUsecaseMock) InvokeCalls() []struct {
	RefreshToken string
} {
	var calls []struct {
		RefreshToken string
	}
	mock.lockInvoke.RLock()
	calls = mock.calls.Invoke
	mock.lockInvoke.RUnlock()
	return calls
}
