// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package user

import (
	"github.com/google/uuid"
	"github.com/sntkn/go-oauth2/oauth2/internal/repository"
	"sync"
)

// Ensure, that GetUserUsecaseMock does implement GetUserUsecase.
// If this is not the case, regenerate this file with moq.
var _ GetUserUsecase = &GetUserUsecaseMock{}

// GetUserUsecaseMock is a mock implementation of GetUserUsecase.
//
//	func TestSomethingThatUsesGetUserUsecase(t *testing.T) {
//
//		// make and configure a mocked GetUserUsecase
//		mockedGetUserUsecase := &GetUserUsecaseMock{
//			InvokeFunc: func(userID uuid.UUID) (repository.User, error) {
//				panic("mock out the Invoke method")
//			},
//		}
//
//		// use mockedGetUserUsecase in code that requires GetUserUsecase
//		// and then make assertions.
//
//	}
type GetUserUsecaseMock struct {
	// InvokeFunc mocks the Invoke method.
	InvokeFunc func(userID uuid.UUID) (repository.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// Invoke holds details about calls to the Invoke method.
		Invoke []struct {
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
	}
	lockInvoke sync.RWMutex
}

// Invoke calls InvokeFunc.
func (mock *GetUserUsecaseMock) Invoke(userID uuid.UUID) (repository.User, error) {
	if mock.InvokeFunc == nil {
		panic("GetUserUsecaseMock.InvokeFunc: method is nil but GetUserUsecase.Invoke was just called")
	}
	callInfo := struct {
		UserID uuid.UUID
	}{
		UserID: userID,
	}
	mock.lockInvoke.Lock()
	mock.calls.Invoke = append(mock.calls.Invoke, callInfo)
	mock.lockInvoke.Unlock()
	return mock.InvokeFunc(userID)
}

// InvokeCalls gets all the calls that were made to Invoke.
// Check the length with:
//
//	len(mockedGetUserUsecase.InvokeCalls())
func (mock *GetUserUsecaseMock) InvokeCalls() []struct {
	UserID uuid.UUID
} {
	var calls []struct {
		UserID uuid.UUID
	}
	mock.lockInvoke.RLock()
	calls = mock.calls.Invoke
	mock.lockInvoke.RUnlock()
	return calls
}
