// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package session

import (
	"github.com/gin-gonic/gin"
	"sync"
)

// Ensure, that SessionClientMock does implement SessionClient.
// If this is not the case, regenerate this file with moq.
var _ SessionClient = &SessionClientMock{}

// SessionClientMock is a mock implementation of SessionClient.
//
//	func TestSomethingThatUsesSessionClient(t *testing.T) {
//
//		// make and configure a mocked SessionClient
//		mockedSessionClient := &SessionClientMock{
//			DelSessionDataFunc: func(c *gin.Context, key string) error {
//				panic("mock out the DelSessionData method")
//			},
//			GetSessionDataFunc: func(c *gin.Context, key string) (string, error) {
//				panic("mock out the GetSessionData method")
//			},
//			PullSessionDataFunc: func(c *gin.Context, key string) (string, error) {
//				panic("mock out the PullSessionData method")
//			},
//			SetSessionDataFunc: func(c *gin.Context, key string, input string) error {
//				panic("mock out the SetSessionData method")
//			},
//		}
//
//		// use mockedSessionClient in code that requires SessionClient
//		// and then make assertions.
//
//	}
type SessionClientMock struct {
	// DelSessionDataFunc mocks the DelSessionData method.
	DelSessionDataFunc func(c *gin.Context, key string) error

	// GetSessionDataFunc mocks the GetSessionData method.
	GetSessionDataFunc func(c *gin.Context, key string) (string, error)

	// PullSessionDataFunc mocks the PullSessionData method.
	PullSessionDataFunc func(c *gin.Context, key string) (string, error)

	// SetSessionDataFunc mocks the SetSessionData method.
	SetSessionDataFunc func(c *gin.Context, key string, input string) error

	// calls tracks calls to the methods.
	calls struct {
		// DelSessionData holds details about calls to the DelSessionData method.
		DelSessionData []struct {
			// C is the c argument value.
			C *gin.Context
			// Key is the key argument value.
			Key string
		}
		// GetSessionData holds details about calls to the GetSessionData method.
		GetSessionData []struct {
			// C is the c argument value.
			C *gin.Context
			// Key is the key argument value.
			Key string
		}
		// PullSessionData holds details about calls to the PullSessionData method.
		PullSessionData []struct {
			// C is the c argument value.
			C *gin.Context
			// Key is the key argument value.
			Key string
		}
		// SetSessionData holds details about calls to the SetSessionData method.
		SetSessionData []struct {
			// C is the c argument value.
			C *gin.Context
			// Key is the key argument value.
			Key string
			// Input is the input argument value.
			Input string
		}
	}
	lockDelSessionData  sync.RWMutex
	lockGetSessionData  sync.RWMutex
	lockPullSessionData sync.RWMutex
	lockSetSessionData  sync.RWMutex
}

// DelSessionData calls DelSessionDataFunc.
func (mock *SessionClientMock) DelSessionData(c *gin.Context, key string) error {
	if mock.DelSessionDataFunc == nil {
		panic("SessionClientMock.DelSessionDataFunc: method is nil but SessionClient.DelSessionData was just called")
	}
	callInfo := struct {
		C   *gin.Context
		Key string
	}{
		C:   c,
		Key: key,
	}
	mock.lockDelSessionData.Lock()
	mock.calls.DelSessionData = append(mock.calls.DelSessionData, callInfo)
	mock.lockDelSessionData.Unlock()
	return mock.DelSessionDataFunc(c, key)
}

// DelSessionDataCalls gets all the calls that were made to DelSessionData.
// Check the length with:
//
//	len(mockedSessionClient.DelSessionDataCalls())
func (mock *SessionClientMock) DelSessionDataCalls() []struct {
	C   *gin.Context
	Key string
} {
	var calls []struct {
		C   *gin.Context
		Key string
	}
	mock.lockDelSessionData.RLock()
	calls = mock.calls.DelSessionData
	mock.lockDelSessionData.RUnlock()
	return calls
}

// GetSessionData calls GetSessionDataFunc.
func (mock *SessionClientMock) GetSessionData(c *gin.Context, key string) (string, error) {
	if mock.GetSessionDataFunc == nil {
		panic("SessionClientMock.GetSessionDataFunc: method is nil but SessionClient.GetSessionData was just called")
	}
	callInfo := struct {
		C   *gin.Context
		Key string
	}{
		C:   c,
		Key: key,
	}
	mock.lockGetSessionData.Lock()
	mock.calls.GetSessionData = append(mock.calls.GetSessionData, callInfo)
	mock.lockGetSessionData.Unlock()
	return mock.GetSessionDataFunc(c, key)
}

// GetSessionDataCalls gets all the calls that were made to GetSessionData.
// Check the length with:
//
//	len(mockedSessionClient.GetSessionDataCalls())
func (mock *SessionClientMock) GetSessionDataCalls() []struct {
	C   *gin.Context
	Key string
} {
	var calls []struct {
		C   *gin.Context
		Key string
	}
	mock.lockGetSessionData.RLock()
	calls = mock.calls.GetSessionData
	mock.lockGetSessionData.RUnlock()
	return calls
}

// PullSessionData calls PullSessionDataFunc.
func (mock *SessionClientMock) PullSessionData(c *gin.Context, key string) (string, error) {
	if mock.PullSessionDataFunc == nil {
		panic("SessionClientMock.PullSessionDataFunc: method is nil but SessionClient.PullSessionData was just called")
	}
	callInfo := struct {
		C   *gin.Context
		Key string
	}{
		C:   c,
		Key: key,
	}
	mock.lockPullSessionData.Lock()
	mock.calls.PullSessionData = append(mock.calls.PullSessionData, callInfo)
	mock.lockPullSessionData.Unlock()
	return mock.PullSessionDataFunc(c, key)
}

// PullSessionDataCalls gets all the calls that were made to PullSessionData.
// Check the length with:
//
//	len(mockedSessionClient.PullSessionDataCalls())
func (mock *SessionClientMock) PullSessionDataCalls() []struct {
	C   *gin.Context
	Key string
} {
	var calls []struct {
		C   *gin.Context
		Key string
	}
	mock.lockPullSessionData.RLock()
	calls = mock.calls.PullSessionData
	mock.lockPullSessionData.RUnlock()
	return calls
}

// SetSessionData calls SetSessionDataFunc.
func (mock *SessionClientMock) SetSessionData(c *gin.Context, key string, input string) error {
	if mock.SetSessionDataFunc == nil {
		panic("SessionClientMock.SetSessionDataFunc: method is nil but SessionClient.SetSessionData was just called")
	}
	callInfo := struct {
		C     *gin.Context
		Key   string
		Input string
	}{
		C:     c,
		Key:   key,
		Input: input,
	}
	mock.lockSetSessionData.Lock()
	mock.calls.SetSessionData = append(mock.calls.SetSessionData, callInfo)
	mock.lockSetSessionData.Unlock()
	return mock.SetSessionDataFunc(c, key, input)
}

// SetSessionDataCalls gets all the calls that were made to SetSessionData.
// Check the length with:
//
//	len(mockedSessionClient.SetSessionDataCalls())
func (mock *SessionClientMock) SetSessionDataCalls() []struct {
	C     *gin.Context
	Key   string
	Input string
} {
	var calls []struct {
		C     *gin.Context
		Key   string
		Input string
	}
	mock.lockSetSessionData.RLock()
	calls = mock.calls.SetSessionData
	mock.lockSetSessionData.RUnlock()
	return calls
}
