name: APIBuildAndPush

on:
  push:
    branches:
      - "**"
    paths:
      - "api/**"
      - ".github/**"
      - "compose.yml"
      - "docker/**"
      - "go.work"
      - "go.work.som"

jobs:
  limeline:
    uses: Kesin11/actions-timeline@v1
    with:
      github-token: ${{ github.token }}
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      target: api
  test:
    uses: ./.github/workflows/test.yml
    permissions:
      contents: read
      packages: write
    with:
      target: api
  build-and-push:
    needs: [lint, test]
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/build-and-push.yml
    permissions:
      contents: read
      packages: write
    with:
      target: api
