name: APIBuildAndPush

on:
  push:
    branches:
      - "**"
    paths:
      - "api/**"
      - ".github/**"
      - "compose.yml"
      - "docker/**"
      - "go.work"
      - "go.work.som"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      target: api
  test:
    uses: ./.github/workflows/test.yml
    secrets:
      DOTENV_PRIVATE_KEY_CI: ${{ secrets.DOTENV_PRIVATE_KEY_CI }}
    permissions:
      contents: read
      packages: write
    with:
      target: api
  build-and-push:
    needs: [lint, test]
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/build-and-push.yml
    permissions:
      contents: read
      packages: write
    with:
      target: api
  actions-timeline:
    needs: [lint, test, build-and-push]
    runs-on: ubuntu-latest
    steps:
    - uses: Kesin11/actions-timeline@v2
      with:
        github-token: ${{ github.token }}
