name: Auto merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-api:
    if: ${{ github.actor == 'dependabot[bot]' || github.event.pull_request.user.login == 'dependabot[bot]' }}
    uses: ./.github/workflows/test.yml
    with:
      target: api
    secrets:
      DOTENV_PRIVATE_KEY_CI: ${{ secrets.DOTENV_PRIVATE_KEY_CI }}
    permissions:
      contents: read
      packages: write
  test-oauth2:
    if: ${{ github.actor == 'dependabot[bot]' || github.event.pull_request.user.login == 'dependabot[bot]' }}
    uses: ./.github/workflows/test.yml
    with:
      target: oauth2
    secrets:
      DOTENV_PRIVATE_KEY_CI: ${{ secrets.DOTENV_PRIVATE_KEY_CI }}
    permissions:
      contents: read
      packages: write
  merge:
    needs: [test-oauth2, test-api]
    if: ${{ github.actor == 'dependabot[bot]' || github.event.pull_request.user.login == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Approve PR
        run: gh pr review "${GITHUB_HEAD_REF}" --approve
      - name: Merge PR
        run: gh pr merge "${GITHUB_HEAD_REF}" --merge --auto
