name: BuildAndPush

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.22.x"]
    env:
      BRANCH_NAME: $(echo ${{ github.ref_name }} | sed -e 's/\//\-/g')
      COMMIT_HASH: ${GITHUB_SHA::7}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      - name: ls
        run: ls -l
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./oauth2
          target: final
          push: true
          tags: sntkn/oauth2:$(echo ${{ github.ref_name }} | sed -e 's/\//\-/g')-${{ env.COMMIT_HASH }}
#      - name: build
#        run: |
#          cd oauth2
#          docker build --target final -t sntkn/oauth2:${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH }} .
#          docker push sntkn/oauth2:${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH }}
