name: assignee and labels
on: pull_request

jobs:
  assignee:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@0a2c53d3721e4c5cfcce6afd4014aecc337979f6 # v2.0.2
    permissions:
      contents: read
      pull-requests: write
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7.0.0
    permissions:
      contents: read
      pull-requests: write
