name: assignee and labels
on: pull_request

jobs:
  assignee:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
    permissions:
      contents: read
      pull-requests: write
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v6
    permissions:
      contents: read
      pull-requests: write
