name: LintAndTest

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
    secrets:
      DOTENV_PRIVATE_KEY_CI:
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: ${{ inputs.target }}/go.mod
          check-latest: true
          cache: true
          cache-dependency-path: ${{ inputs.target }}/go.sum

      - name: Compose Build & UP
        run: |
          docker compose up -d database kvs
      - name: Log
        run: docker compose logs database

      - name: Wait for Services
        run: ./docker/wait-for-services.sh

      - name: Log
        run: docker compose logs database

      - name: Test
        env:
          DOTENV_PRIVATE_KEY_CI: ${{ secrets.DOTENV_PRIVATE_KEY_CI }}
        run: |
          cd ${{ inputs.target }}
          go test -v ./...
