name: LintAndTest

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ inputs.target }}/go.mod
          check-latest: true
          cache-dependency-path: |
              ${{ inputs.target }}/go.sum
      # 1. Buildxのセットアップ
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker database image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/database
          load: true
          tags: test-db
          cache-from: type=gha
          cache-to: type=gha,mode=max
          no-cache: false

      - name: Build and push Docker session image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/session
          load: true
          tags: test-session
          cache-from: type=gha
          cache-to: type=gha,mode=max
          no-cache: false

      # 6. docker composeビルド/起動
      - name: Compose Build & UP
        run: |
          docker compose up -d database session

      - name: Wait for Services
        run: ./docker/wait-for-services.sh

      - name: Log
        run: docker compose logs database

      # 7. テスト実行
      - name: Test
        run: |
          cd ${{ inputs.target }}
          go test -v ./...
      - name: Compose Down
        run: docker compose down
      - name: Change volume permissions
        run: |
          sudo chown -R $USER:$USER ./docker/pgdata
