name: LintAndTest

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'oauth2/go.mod'
          check-latest: true
          cache-dependency-path: |
              oauth2/go.sum
      # 1. Buildxのセットアップ
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Build and push Docker database image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/database
          push: true
          tags: ${{ steps.meta.outputs.tags }}-db
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}-db # キャッシュを指定
          cache-to: type=inline # キャッシュを指定
      - name: Build and push Docker session image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/session
          push: true
          tags: ${{ steps.meta.outputs.tags }}-session
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}-session # キャッシュを指定
          cache-to: type=inline # キャッシュを指定

      # 4. docker composeビルド/起動
      - name: docker compose build & up
        run: |
          docker buildx build --cache-from type=registry,ref=${{ steps.meta.outputs.tags }}-db ./docker/database --load
          docker buildx build --cache-from type=registry,ref=${{ steps.meta.outputs.tags }}-session ./docker/session --load
          docker buildx bake -f compose.yml
          docker compose up -d

      # 5. テスト実行
      - name: Test
        run: |
          docker compose exec server go test -v ./...
