name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Buildxのセットアップ
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      # 2. キャッシュ設定
      - name: Cache Docker layers - App
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-app # Buildxのキャッシュを指定
          key: ${{ github.ref }}-${{ github.sha }} # キャッシュのキーを指定
          restore-keys: |
            ${{ github.ref }}
            refs/head/main

      - name: Cache Docker layers - Database
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-database # Buildxのキャッシュを指定
          key: ${{ github.ref }}-${{ github.sha }} # キャッシュのキーを指定
          restore-keys: |
            ${{ github.ref }}
            refs/head/main

      # 3. Buildxでイメージをビルドする
      - name: Build images - App
        uses: docker/build-push-action@v5
        with:
          push: false
          builder: ${{ steps.buildx.outputs.name }} # Buildxでビルドすることを指定
          tags: testapp-app-cached:latest # イメージ名を指定/docker-compose.ymlで参照する名前
          load: true
          context: ./oauth2
          cache-from: type=local,src=/tmp/.buildx-cache-app # キャッシュを指定
          cache-to: type=local,dest=/tmp/.buildx-cache-new-app # キャッシュを指定

      - name: Build images - Database
        uses: docker/build-push-action@v5
        with:
          push: false
          builder: ${{ steps.buildx.outputs.name }} # Buildxでビルドすることを指定
          tags: testapp-database-cached:latest # イメージ名を指定/docker-compose.ymlで参照する名前
          load: true
          context: ./docker/database
          cache-from: type=local,src=/tmp/.buildx-cache-database # キャッシュを指定
          cache-to: type=local,dest=/tmp/.buildx-cache-new-database # キャッシュを指定

      - name: Build images - Session
        uses: docker/build-push-action@v5
        with:
          push: false
          builder: ${{ steps.buildx.outputs.name }} # Buildxでビルドすることを指定
          tags: testapp-session-cached:latest # イメージ名を指定/docker-compose.ymlで参照する名前
          load: true
          context: ./docker/session
          cache-from: type=local,src=/tmp/.buildx-cache-session # キャッシュを指定
          cache-to: type=local,dest=/tmp/.buildx-cache-new-session # キャッシュを指定

      # 4. docker composeビルド/起動
      - name: docker compose build & up
        run: |
          docker compose -f compose.ci.yml build
          docker compose -f compose.ci.yml up -d

      # 5. テスト実行
      - name: Test
        run: |
          docker compose -f compose.ci.yml run --rm server go test -v ./...

      # 6. 肥大化対策
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Update cache
        run: |
          rm -rf /tmp/.buildx-cache-app
          rm -rf /tmp/.buildx-cache-database
          rm -rf /tmp/.buildx-cache-session
          mv /tmp/.buildx-cache-new-app /tmp/.buildx-cache-app
          mv /tmp/.buildx-cache-new-database /tmp/.buildx-cache-database
          mv /tmp/.buildx-cache-new-session /tmp/.buildx-cache-session
