name: LintAndTest

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ inputs.target }}/go.mod
          check-latest: true
          cache-dependency-path: |
              ${{ inputs.target }}/go.sum

      - name: Cache database image
        uses: docker/build-push-action@v5
        with:
          load: true
          tags: postgres:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          no-cache: false

      - name: Cache session image
        uses: docker/build-push-action@v5
        with:
          load: true
          tags: redis:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          no-cache: false

      - name: Compose Build & UP
        run: |
          docker compose up -d database session

      - name: Wait for Services
        run: ./docker/wait-for-services.sh

      - name: Log
        run: docker compose logs database

      - name: Test
        run: |
          cd ${{ inputs.target }}
          go test -v ./...
